### PR TITLE
Ipxgw ethernetii bugfixes

### PR DESCRIPTION
**Pull request by superfury**
A little improvement on the IPX receiving (from both sides of the connection) to increase the transControl field in the IPX header. This allows connected clients to identify the packet having been routed through a IPX router and also makes detection of IPX echo vs echo replies possible (to prevent deadlocking on my own emulator, which won't send a IPX reply if it's increased past 1, to prevent replying to it's own IPX replies and flooding it's own network and causing a deadlock on itself).

I've also fixed some issue on the IPX reply check during allocation to actually check the fields in the header that was received, as inPacket isn't filled with the data when receiving packets from the Ethernet II connection.

### CODE REVIEW

**Comment by superfury** [comment]
I've just also added some fixup of the source network for packets sent from Dosbox. So if it specifies 'current network' (network number 0) in the source address field, it'll replace that with the client's network, making it detectable when receiving the packet (improving compatibility). That fixed non-zero specified network numbers when configured to use a non-zero network number. Dosbox's 'ipxnet ping' is fixed with that as well, as are it's echo replies (since those always use source network zero or reply using that network number).

**Comment by superfury** [comment]
Fixed the new code to compile properly (missed some parameters etc.). It should now patch the sourve network number correctly if zeroed.

**Comment by superfury** [comment]
Just added another small improvement. It will display the network number used if specified.

**Comment by superfury** [comment]
Also added autotools support while I was at it. Just tested with Ubuntu 18.04.1 LTS though (newer versions of Ubuntu currently don't seem to work in Virtualbox I'm testing this app with).

**Comment by superfury** [comment]
It seems that the addition of the displaying of network number being adjusted to non-zero (or specified at all) undid some previous commits, so I reverse commited them back.

**Comment by superfury** [comment]
And a slight bugfix in the network patching: properly patch the source network to the client's own network number instead of the destination network. Didn't notice that until testing it.

**Comment by superfury** [comment]
Improved the IPX echo request and reply pType fields a bit. Now they more accurately implement them according to documentation.

I've also added some optional logging of receiving of IPX node numbers. Oddly enough I see a part of the node number being increased by 1 of what's expected? Hmmm...
Edit: Perhaps one of the ++ operations are operating on the wrong byte? I see a broadcast returning as a zeroed byte for the first byte of the node number? A misaligned packet pointer perhaps?

**Comment by superfury** [comment]
OK. There was an issue in the IPX packet pointer that incidentally also updates the amount of hops (from IPv4 terminology) when receiving an IPX packet from the host network. It was using an invalid offset from the ethernet II header for that (0x14 instead of 14). Thus it would increase the first byte of the IPX source address of received packets instead.

"ipxnet ping" seems to run without issues now. Although it gets double or for some hosts even triple echo packets back (from UniPCemu's packet server)? Two out of the 3 UniPCemu Dosbox-X Win95 clients give double replies and one client even triple replies? That's weird? Afaik each client will only send 1 echo packet (with pType=2, whereas it's requests have pType=0). So why is Dosbox receiving 7 instead of 3 replies? That's weird?

Otherwise, it's running properly (Doom still can't handle more than 1 Win95(+1 DOS) clients though. Everytime I use more than 1 Windows client with any amount of MS-DOS clients, the MS-DOS client starts 'spinning' on the next node location or top right corner (with 4 nodes) and won't continue?).

**Comment by ksalin** [comment]
The changes look good, merging these as they should also fix the code to compile again

**Pull request merged**
